/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segmentation;

/**
 *
 * @author lasroun
 */
public class MLSegmentationJavaView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MLSegmentationJavaView.class.getName());

    /**
     * Creates new form MLSegmentationJavaView
     */
    public MLSegmentationJavaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Valider");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel1.setText("Choisir le fichier CSV ou entrez son chemin");

        jButton2.setText("...");
        jButton2.setToolTipText("");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String chemin = jTextField1.getText().trim(); // .trim() enlève les espaces inutiles au début/fin du string

        // Créer un objet File avec le chemin entré
        java.io.File fichier = new java.io.File(chemin);

        // Vérifications successives
        if (chemin.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le champ est vide. Veuillez choisir un fichier.", "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        } 
        else if (!fichier.exists()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le fichier n'existe pas !\nVérifiez le chemin saisi.", "Chemin invalide", javax.swing.JOptionPane.ERROR_MESSAGE);
        } 
        else if (!chemin.toLowerCase().endsWith(".csv")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Le fichier doit être au format .csv", "Format incorrect", javax.swing.JOptionPane.WARNING_MESSAGE);
        } 
        else {
            // Si tout est OK
            javax.swing.JOptionPane.showMessageDialog(this, "Fichier valide ! Prêt pour l'analyse Weka.", "Succès", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
            System.out.println("Lancement de l'analyse pour : " + chemin);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Créer la fenêtre de choix de fichier
        javax.swing.JFileChooser fc = new javax.swing.JFileChooser();

        // Afficher la fenêtre et stocker le résultat (ouvrir ou annuler)
        int resultat = fc.showOpenDialog(this);

        // Si l'utilisateur a choisi un fichier
        if (resultat == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File fichier = fc.getSelectedFile();
    
        // On écrit le chemin dans le champ texte
        jTextField1.setText(fichier.getAbsolutePath());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MLSegmentationJavaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
